In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
edge_servers = pd.read_csv ('../edge-servers/site.csv')

In [3]:
edge_servers

,SITE_ID,LATITUDE,LONGITUDE,NAME,STATE,LICENSING_AREA_ID,POSTCODE,SITE_PRECISION,ELEVATION,HCIS_L2
0,1000,-12.471947,130.845073,Fort Hill Wharf DARWIN,NT,4,800.0,Unknown,NaN,GO7H
1,10000,-33.756158,150.698182,Cnr Castlereagh & Lethbri PENRITH,NSW,2,2750.0,Unknown,NaN,MV9O
2,10000002,-28.777660,114.634260,Optus 50m Lattice Tower 71 Eastward Road Utakarra,WA,4,NaN,Within 10 meters,NaN,AU3O
3,10000003,-12.464597,130.840708,6 Knuckey Street Darwin,NT,4,NaN,Within 10 meters,NaN,GO7H
4,10000004,-39.596400,143.933900,Cape Wickham Links Clubhouse KING ISLAND,TAS,5,NaN,Within 100 meters,NaN,KX8L
...,...,...,...,...,...,...,...,...,...,...
95557,9989,-33.752425,150.696231,114-116 Henry St Rds PENRITH,NSW,2,2750.0,Within 10 meters,NaN,MV9O
95558,9993,-33.730815,150.697780,5 Andrews Rd PENRITH,NSW,2,2750.0,Unknown,NaN,MV9K
95559,9995,-33.752834,150.698811,CMTS Site 90-92 Henry St PENRITH,NSW,2,2750.0,Within 10 meters,39.0,MV9O
95560,9997,-33.750361,150.696718,Railway Station Belmore St PENRITH,NSW,2,2750.0,Unknown,35.0,MV9O
95561,9999,-33.755818,150.699271,Cnr Castle Reagh & Lethbridge Sts PENRITH,NSW,2,2750.0,Unknown,NaN,MV9O

In [125]:
users = pd.read_csv('users/users-aus.csv')

In [126]:
take = users.shape[0]
percent = 25
x = (1.00*percent/100) * take
users = users.loc[:x]
users

                IP  Latitude  Longitude  PostCode         City State Country
0        1.120.0.1  -30.5083   151.6712    2350.0     Armidale   NSW      AU
1        1.120.2.1  -37.8833   145.3333    3786.0  Ferny Creek   VIC      AU
2        1.120.8.1  -32.2430   148.6048    2830.0        Dubbo   NSW      AU
3       1.120.32.1  -37.8141   144.9630       NaN    Melbourne   VIC      AU
4       1.120.96.1  -27.4891   153.0188    4101.0     Brisbane   QLD      AU
...            ...       ...        ...       ...          ...   ...     ...
1183  101.160.22.1  -37.7333   145.2667    3115.0   Wonga Park   VIC      AU
1184  101.160.36.1  -38.1748   144.3428    3216.0      Belmont   VIC      AU
1185  101.160.38.1  -37.7667   144.9167    3040.0     Essendon   VIC      AU
1186  101.160.39.1  -38.3000   145.1833    3915.0     Hastings   VIC      AU
1187  101.160.44.1  -37.0563   142.7809    3380.0      Stawell   VIC      AU

[1188 rows x 7 columns]

In [4]:
def getRadian (deg):
    return ((deg * np.pi) / 180.0)
def distanceBetweenPoints (latitude1 , longitude1 , latitude2 , longitude2):
    radiusOfEarth = 6378.1
    lat1 = getRadian(latitude1)
    lat2 = getRadian(latitude2)
    long1 = getRadian(longitude1)
    long2 = getRadian(longitude2)
    return radiusOfEarth * math.acos((math.sin(lat1)*math.sin(lat2))+math.cos(lat1)*math.cos(lat2)*math.cos(long2-long1))
def getArea (distance):
    return np.pi * distance * distance

In [5]:
# verified values online
print(distanceBetweenPoints(-30.5083,151.6712,-30,150))

170.36619567739388

## EXPERIMENTAL SETUP

In [7]:
NUMBER_OF_SERVERS = 55
COVERAGE_LOW = 100
COVERAGE_HIGH = 150

In [8]:
filtered_edges = edge_servers.head(NUMBER_OF_SERVERS)
filtered_edges = filtered_edges[['SITE_ID', 'LATITUDE' , 'LONGITUDE' , 'STATE' ]]
filtered_edges['COVERAGE'] = np.random.uniform(low = COVERAGE_LOW , high = COVERAGE_HIGH , size = NUMBER_OF_SERVERS)
filtered_edges

     SITE_ID   LATITUDE   LONGITUDE STATE    COVERAGE
0       1000 -12.471947  130.845073    NT  148.505342
1      10000 -33.756158  150.698182   NSW  136.867226
2   10000002 -28.777660  114.634260    WA  110.805424
3   10000003 -12.464597  130.840708    NT  139.653617
4   10000004 -39.596400  143.933900   TAS  132.450029
5   10000006 -28.913583  153.320278   NSW  136.852802
6   10000007 -32.673730  152.183366   NSW  120.235774
7   10000008 -33.554239  150.733037   NSW  143.291540
8   10000009 -36.416261  143.611158   VIC  146.007412
9   10000010 -33.315074  115.726263    WA  141.937302
10  10000011 -33.307414  115.734614    WA  143.586005
11  10000012 -33.357333  115.624897    WA  119.658058
12  10000013 -28.687008  153.523194   NSW  127.116634
13  10000014 -31.540083  116.372957    WA  104.977938
14  10000015 -31.549951  116.453282    WA  100.676468
15  10000016 -33.831142  115.106278    WA  142.437196
16  10000017 -33.629218  115.091635    WA  123.198746
17  10000018 -27.806743  152.640874   QLD  115.082177
18  10000019 -23.358303  120.780766    WA  127.034727
19  10000020 -28.074596  152.856728   QLD  142.370988
20  10000021 -33.864266  121.877509    WA  113.161688
21  10000022 -37.814712  144.974322   VIC  129.679252
22  10000023 -37.651230  144.959774   VIC  130.394347
23  10000024 -38.229606  146.414233   VIC  146.812248
24  10000025 -38.195525  146.561853   VIC  149.087053
25  10000026 -33.718700  150.834100   NSW  109.624826
26  10000027 -37.810900  144.937100   VIC  110.483871
27  10000028 -37.916514  145.038261   VIC  114.969819
28  10000029 -33.787600  150.881500   NSW  115.577923
29  10000030 -37.919200  145.346300   VIC  102.761931
30  10000031 -37.690500  145.024800   VIC  149.678927
31  10000032 -33.947875  150.899139   NSW  135.780948
32  10000033 -37.574405  144.920440   VIC  122.195474
33  10000034 -33.861242  151.208261   NSW  111.000123
34  10000035 -33.869040  151.206950   NSW  139.358989
35  10000036 -33.879819  151.205344   NSW  108.932611
36  10000037 -33.885622  151.206908   NSW  142.184985
37  10000038 -33.889967  151.217889   NSW  104.963660
38  10000039 -33.907164  151.226875   NSW  118.748682
39  10000040 -33.917272  151.241247   NSW  111.468234
40  10000041 -33.915572  151.225783   NSW  121.602681
41  10000042 -33.925697  151.230031   NSW  110.424256
42  10000043 -33.874169  151.164822   NSW  148.690954
43  10000044 -33.879589  151.147250   NSW  106.098436
44  10000045 -33.889294  151.145194   NSW  107.859902
45  10000046 -33.910111  151.234939   NSW  135.636862
46  10000047 -37.857886  144.789906   VIC  148.043463
47  10000048 -37.805036  144.932034   VIC  106.886527
48  10000049 -37.416821  145.005337   VIC  101.292434
49  10000050 -38.103396  147.054383   VIC  112.571157
50  10000051 -30.775337  121.441999    WA  123.367407
51  10000052 -12.630833  141.880833   QLD  144.801295
52  10000054 -31.955191  115.876073    WA  124.101392
53  10000055 -31.933208  115.866616    WA  128.639110
54  10000057 -19.262380  146.810800   QLD  144.793091

In [131]:
numServers = filtered_edges.shape[0]
cnt = 0
edgeServerSiteId = []
uId = []
edgeServersLatList = []
edgeServersLongList = []
edgeServersStateList = []
edgeServersCoverageList = []
usersLatList = []
usersLongList = []

for index in range (numServers):
    if (index % 10 == 0):
        print(index)
    site = filtered_edges.iloc[index]['SITE_ID']
    latitude = filtered_edges.iloc[index]['LATITUDE']
    longitude = filtered_edges.iloc[index]['LONGITUDE']
    coverage = filtered_edges.iloc[index]['COVERAGE']
    numUsers = users.shape[0]
    for userId in range(numUsers):
        userLat = users.iloc[userId]['Latitude']
        userLong = users.iloc[userId]['Longitude']
        distance_eua = distanceBetweenPoints (latitude, longitude, userLat, userLong)
        if (distance_eua <= coverage):
            usersLatList.append(userLat)
            usersLongList.append(userLong)
            edgeServersLatList.append(latitude)
            edgeServersLongList.append(longitude)
            edgeServersCoverageList.append(coverage)
            edgeServerSiteId.append(site)
            uId.append (userId)

0
10
20
30
40
50

In [132]:
eua_data_set = pd.DataFrame()
eua_data_set['siteId'] = edgeServerSiteId
eua_data_set['serverLat'] = edgeServersLatList
eua_data_set['serverLong'] = edgeServersLongList
eua_data_set['coverage'] = edgeServersCoverageList
eua_data_set['uId'] = uId;
eua_data_set['userLat'] = usersLatList
eua_data_set['userLong'] = usersLongList

In [133]:
eua_data_set.to_csv('eua_experiment.csv')